import type {
  AuditLogEntry,
  AuditLogListResponse,
  AuditLogQueryParams,
  AuditLogStats,
  AuthonOrganization,
  AuthonProvider,
  AuthonSession,
  AuthonUser,
  AuthTokens,
  BrandingConfig,
  CreateJwtTemplateParams,
  CreateOrganizationParams,
  InviteMemberParams,
  JwtClaimMapping,
  JwtPreviewResponse,
  JwtTemplate,
  MfaSetupResponse,
  MfaStatus,
  MfaVerifyResponse,
  OAuthProviderType,
  OrganizationInvitation,
  OrganizationListResponse,
  OrganizationMember,
  PasskeyCredential,
  PasswordlessResult,
  SessionConfig,
  SessionInfo,
  UpdateJwtTemplateParams,
  UpdateOrganizationParams,
  Web3Chain,
  Web3NonceResponse,
  Web3Wallet,
  Web3WalletType,
  WebhookEvent,
  WebhookEventType,
} from '../../packages/shared/src/index';
import type {
  AuthonConfig,
  AuthonEvents,
  AuthonEventType,
  AuthonLocale,
  OAuthFlowMode,
  OAuthSignInOptions,
  ProviderButtonConfig,
  TranslationStrings,
} from '../../packages/js/src/index';
import type {
  AuthonContextValue,
  BrandingState,
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  InputProps,
  LinkWalletParams,
  SignInProps,
  SignUpProps,
  SocialButtonProps,
  SocialButtonsProps,
  UseAuthonMfaReturn,
  UseAuthonPasskeysReturn,
  UseAuthonPasswordlessReturn,
  UseAuthonSessionsReturn,
  UseAuthonWeb3Return,
  UseOrganizationListReturn,
  UseOrganizationReturn,
  UserButtonProps,
  UserProfileProps,
} from '../../packages/react/src/index';
import type { AuthonMiddlewareOptions } from '../../packages/nextjs/src/index';
import type { AuthonPluginOptions, AuthonState } from '../../packages/vue/src/index';
import type { AuthonModuleOptions, AuthonPluginState } from '../../packages/nuxt/src/index';
import type { AuthonStore, SocialButtonsOptions } from '../../packages/svelte/src/index';
import type { AuthonServiceConfig, SocialButtonsConfig } from '../../packages/angular/src/index';
import type {
  AuthonReactNativeConfig,
  AuthState,
  OAuthCompletedResponse,
  OAuthErrorResponse,
  SignInParams,
  SignUpParams,
  StartOAuthOptions,
  TokenPair,
  Web3LinkWalletParams,
} from '../../packages/react-native/src/index';

type PublicTypes = [
  AuditLogEntry,
  AuditLogListResponse,
  AuditLogQueryParams,
  AuditLogStats,
  AuthonOrganization,
  AuthonProvider,
  AuthonSession,
  AuthonUser,
  AuthTokens,
  BrandingConfig,
  CreateJwtTemplateParams,
  CreateOrganizationParams,
  InviteMemberParams,
  JwtClaimMapping,
  JwtPreviewResponse,
  JwtTemplate,
  MfaSetupResponse,
  MfaStatus,
  MfaVerifyResponse,
  OAuthProviderType,
  OrganizationInvitation,
  OrganizationListResponse,
  OrganizationMember,
  PasskeyCredential,
  PasswordlessResult,
  SessionConfig,
  SessionInfo,
  UpdateJwtTemplateParams,
  UpdateOrganizationParams,
  Web3Chain,
  Web3NonceResponse,
  Web3Wallet,
  Web3WalletType,
  WebhookEvent,
  WebhookEventType,
  AuthonConfig,
  AuthonEvents,
  AuthonEventType,
  AuthonLocale,
  OAuthFlowMode,
  OAuthSignInOptions,
  ProviderButtonConfig,
  TranslationStrings,
  AuthonContextValue,
  BrandingState,
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  InputProps,
  LinkWalletParams,
  SignInProps,
  SignUpProps,
  SocialButtonProps,
  SocialButtonsProps,
  UseAuthonMfaReturn,
  UseAuthonPasskeysReturn,
  UseAuthonPasswordlessReturn,
  UseAuthonSessionsReturn,
  UseAuthonWeb3Return,
  UseOrganizationListReturn,
  UseOrganizationReturn,
  UserButtonProps,
  UserProfileProps,
  AuthonMiddlewareOptions,
  AuthonPluginOptions,
  AuthonState,
  AuthonModuleOptions,
  AuthonPluginState,
  AuthonStore,
  SocialButtonsOptions,
  AuthonServiceConfig,
  SocialButtonsConfig,
  AuthonReactNativeConfig,
  AuthState,
  OAuthCompletedResponse,
  OAuthErrorResponse,
  SignInParams,
  SignUpParams,
  StartOAuthOptions,
  TokenPair,
  Web3LinkWalletParams,
];

type PublicValues = [
  typeof import('../../packages/shared/src/index'),
  typeof import('../../packages/js/src/index'),
  typeof import('../../packages/react/src/index'),
  typeof import('../../packages/nextjs/src/index'),
  typeof import('../../packages/vue/src/index'),
  typeof import('../../packages/nuxt/src/index'),
  typeof import('../../packages/svelte/src/index'),
  typeof import('../../packages/angular/src/index'),
  typeof import('../../packages/react-native/src/index'),
];

export type AuthonPublicApiCompatibilityFixture = {
  types: PublicTypes;
  values: PublicValues;
};
